apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.23.5
controlPlaneEndpoint: ${CONTROLPLANE_ENDPOINT}
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    cloud-provider: external #disardan aliyorum
    enable-aggregator-routing: "true"  # daha fazla master olacak trafigi toplayip route etmek icin icin
controllerManager:
  extraArgs:
    cloud-provider: external
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration # for cluster starting 
nodeRegistration: # new node register 
  kubeletExtraArgs: # ekstra set
    cloud-provider: external
---
kind: KubeletConfiguration  #  
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd